/*! MAIN bundle — laden in footer, site-breed
    Dutch Boat Factory — samengesteld 2026-08-07.
    Elke module is een op zichzelf staande IIFE en activeert alleen waar zijn element bestaat. */

/* ===================== hero_video_background_v1-6.0.0.js ===================== */
(function(){document.querySelectorAll('[data-video-url]').forEach(function(el){var url=el.getAttribute('data-video-url');var poster=el.getAttribute('data-poster-url');if(!url)return;var fill='position:absolute;top:0;left:0;width:100%;height:100%;pointer-events:none;';if(poster){var ph=document.createElement('div');ph.style.cssText=fill+'background:#000 url("'+poster+'") center/cover no-repeat;';el.appendChild(ph);}var v=document.createElement('video');v.loop=true;v.muted=true;v.defaultMuted=true;v.playsInline=true;v.preload='auto';v.setAttribute('autoplay','');v.setAttribute('muted','');v.setAttribute('playsinline','');v.setAttribute('webkit-playsinline','');v.style.cssText=fill+'object-fit:cover;opacity:0;';v.addEventListener('playing',function(){window.__heroVideoPlaying=true;v.style.opacity='1';});function ok(){return !v.paused&&v.currentTime>0;}function tryPlay(){var p=v.play();if(p&&p.catch)p.catch(function(){});}['loadeddata','canplay','canplaythrough'].forEach(function(ev){v.addEventListener(ev,tryPlay);});el.appendChild(v);v.src=url;tryPlay();var tries=0,pt=setInterval(function(){if(ok()||tries++>40){clearInterval(pt);return;}tryPlay();},400);var once=function(){tryPlay();document.removeEventListener('touchstart',once);document.removeEventListener('click',once);};document.addEventListener('touchstart',once,{passive:true});document.addEventListener('click',once);});})();

/* ===================== sitecartv1-1.0.0.js ===================== */
(function(){var s=document.createElement('style');s.textContent='.cart-float{opacity:0!important;pointer-events:none!important}.cart-float.has-items{opacity:1!important;pointer-events:auto!important}';document.head.appendChild(s);var n=0;function go(){var fl=document.querySelector('.cart-float');if(!fl||typeof window.addToCart!=='function')return false;try{var c=JSON.parse(localStorage.getItem('dc')||'[]');if(c.length)fl.classList.add('has-items');}catch(e){}var orig=window.addToCart;window.addToCart=function(p){fl.classList.add('has-items');return orig(p);};return true;}var t=setInterval(function(){if(go()||++n>100)clearInterval(t);},50);})();(function(){var s=document.createElement('style');s.textContent='@media(max-width:991px){.cart-drawer-checkout:hover .cco-container{background-color:#f15a24!important}.cart-drawer-checkout:hover .cco-icon-l{transform:translateX(-3rem)!important}.cart-drawer-checkout:hover .cco-text{transform:none!important}.cart-drawer-checkout:hover .cco-icon-r{opacity:1!important;transform:translateX(0)!important}}';document.head.appendChild(s);})();

/* ===================== siteuxv1-1.0.0.js ===================== */
(function(){var s=document.createElement('style');s.textContent='.faq_title{transition:color 0.3s ease}.faq_title.is-number{color:#f15a24!important}.faq_item.is-open .faq_title,.faq_item.w--open .faq_title{color:#f15a24!important}';document.head.appendChild(s);function init(){document.querySelectorAll('.faq_header').forEach(function(h){h.addEventListener('click',function(){var item=h.closest('.faq_item');if(!item)return;var wasOpen=item.classList.contains('is-open');document.querySelectorAll('.faq_item.is-open').forEach(function(i){i.classList.remove('is-open');});if(!wasOpen)item.classList.add('is-open');});});}if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init);}else{init();}})();(function(){var s=document.createElement('style');s.textContent='.service_icon-close{transition:color 0.3s ease,transform 0.3s ease}.js-accordion-header:hover .service_icon-close,.js-accordion-item.active .service_icon-close{color:#fff!important}';document.head.appendChild(s);})();

/* ===================== sitecontentv1-2.0.0.js ===================== */
(function(){var map={xl:'200',l:'300'};var re=/\[(xl|l)\]([\s\S]*?)\[\/\1\]/gi;function rep(n){var t=n.nodeValue;if(!re.test(t))return;re.lastIndex=0;var f=document.createDocumentFragment(),last=0,m;while((m=re.exec(t))!==null){if(m.index>last)f.appendChild(document.createTextNode(t.slice(last,m.index)));var s=document.createElement('span');s.style.fontWeight=map[m[1].toLowerCase()];s.textContent=m[2];f.appendChild(s);last=m.index+m[0].length;}if(last<t.length)f.appendChild(document.createTextNode(t.slice(last)));n.parentNode.replaceChild(f,n);}function parse(root){var w=document.createTreeWalker(root||document.body,NodeFilter.SHOW_TEXT,{acceptNode:function(n){return/\[(xl|l)\]/i.test(n.nodeValue)?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_SKIP;}});var ns=[];while(w.nextNode())ns.push(w.currentNode);ns.forEach(rep);}function init(){parse();setTimeout(parse,300);var obs=new MutationObserver(function(muts){muts.forEach(function(m){m.addedNodes.forEach(function(n){if(n.nodeType===1)parse(n);});});});obs.observe(document.body,{childList:true,subtree:true});}if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init);}else{init();}})();(function(){function init(){var s=document.querySelectorAll('.navmobile_slider');if(!s.length)return;var o=false,h=document.documentElement;function ck(ht){if(ht>0&&!o){o=true;h.style.overflow='hidden';if(window.lenis)window.lenis.stop();}else if(ht<=0&&o){o=false;h.style.overflow='';if(window.lenis)window.lenis.start();}}for(var i=0;i<s.length;i++){(function(el){new ResizeObserver(function(en){ck(en[0].contentRect.height);}).observe(el);})(s[i]);}}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();

/* ===================== navscrollrevealv36-36.0.0.js ===================== */
(function(){var W=window,R=requestAnimationFrame;function init(){var a=document.querySelectorAll('.nav_component');if(!a.length)return;var c='w-variant-76070edc-de0a-6356-cffa-3e8ad1a76578';var t=null,b=null;for(var i=0;i<a.length;i++){if(a[i].classList.contains(c))t=a[i];else if(!b)b=a[i];}if(t&&b){if(W.innerWidth<=767){t.style.display='none';def(b,false);}else{home(t,b);}}else{def(a[0],true);}}function def(n,sp){var h=n.offsetHeight,s=null;if(sp){s=document.createElement('div');s.style.height=h+'px';n.parentNode.insertBefore(s,n);}n.style.position='fixed';n.style.top='0';n.style.left='0';n.style.right='0';n.style.transition='top 300ms ease';var l=W.scrollY||0,k=false;function u(){var y=W.scrollY||0;if(!bz()){if(y<=0||y<l-2){n.style.top='0';}else if(y>l+2){n.style.top=(-h)+'px';}}l=y;k=false;}W.addEventListener('scroll',function(){if(!k){R(u);k=true;}},{passive:true});W.addEventListener('resize',function(){h=n.offsetHeight;if(s)s.style.height=h+'px';});}function home(t,b){b.style.position='fixed';b.style.top='0';b.style.left='0';b.style.right='0';var h=b.offsetHeight,l=W.scrollY||0,v=true;function g(){return t.getBoundingClientRect().bottom<=0;}function q(){return t.getBoundingClientRect().top>=0;}var p=g(),k=false,m=null;function tr(x){b.style.transition=(x?'top 300ms ease, ':'')+'opacity 300ms ease';}function fa(){b.style.opacity=p?'1':'0';b.style.pointerEvents=p?'':'none';}function ap(){b.style.top=v?'0':(-h)+'px';fa();}ap();b.offsetHeight;tr(true);function u(){var y=W.scrollY||0;if(!bz()){if(y<=0||y<l-2)v=true;else if(y>l+2)v=false;}var w=p;if(!p&&g())p=true;else if(p&&q())p=false;if(p!==w){tr(false);b.style.top=v?'0':(-h)+'px';b.offsetHeight;fa();clearTimeout(m);m=setTimeout(tr,320,true);}else{ap();}l=y;k=false;}W.addEventListener('scroll',function(){if(!k){R(u);k=true;}},{passive:true});}function bz(){return W.$&&W.$('html').is(':animated');}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();

/* ===================== h2revealmaskv9-10.0.0.js ===================== */
(function(){var DUR=400,ST=130,EA='cubic-bezier(0.33,1,0.68,1)',C=document.createElement.bind(document);function getLines(el){var W=document.createTreeWalker(el,4,null,false),n,py=null,lbs=[];while(n=W.nextNode()){for(var i=0;i<n.nodeValue.length;i++){if(/\s/.test(n.nodeValue[i]))continue;var r=document.createRange();r.setStart(n,i);r.setEnd(n,i+1);var y=r.getBoundingClientRect().top|0;if(py===null||y!==py)lbs.push({n:n,o:i});py=y;}}if(lbs.length<2)return null;var res=[];for(var li=0;li<lbs.length;li++){var rng=document.createRange(),d=C('div');if(li===0){rng.setStartBefore(el.firstChild);}else{rng.setStart(lbs[li].n,lbs[li].o);}if(li<lbs.length-1){rng.setEnd(lbs[li+1].n,lbs[li+1].o);}else{rng.setEndAfter(el.lastChild);}d.appendChild(rng.cloneContents());res.push(d.innerHTML);}return res;}function reveal(el){var h=el.innerHTML,lh=el.offsetHeight;el.style.minHeight=lh+'px';var p=h.split(/<br\s*\/?>/i).filter(function(s){return s.trim();}),ins=[];el.innerHTML='';function mk(c){var m=C('div');m.style.cssText='overflow:hidden;display:block;line-height:inherit';var i=C('div');i.style.cssText='transform:translateY(105%);display:block;line-height:inherit';i.innerHTML=c;m.appendChild(i);el.appendChild(m);ins.push(i);}if(p.length>1){for(var j=0;j<p.length;j++)mk(p[j]);}else{el.innerHTML=h;var lhs=getLines(el)||[h];el.innerHTML='';lhs.forEach(function(c){mk(c);});}el.offsetHeight;el.style.setProperty('visibility','visible','important');requestAnimationFrame(function(){requestAnimationFrame(function(){ins.forEach(function(n,d){setTimeout(function(){n.style.transition='transform '+DUR+'ms '+EA;n.style.transform='translateY(0)';},d*ST);});setTimeout(function(){el.style.minHeight='';},DUR+ins.length*ST+50);});});}function init(){var els=document.querySelectorAll('.heading-style-h2,.hdpro_title');if(!els.length)return;var io=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting){reveal(e.target);io.unobserve(e.target);}});},{threshold:0.3});els.forEach(function(e){io.observe(e);});}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();

/* ===================== eyebrowtypewriterv6-6.0.0.js ===================== */
(function(){var SPEED=20;function typewrite(el){if(el._tw)return;el._tw=true;var w=document.createTreeWalker(el,NodeFilter.SHOW_TEXT,null,false),ns=[],n;while(n=w.nextNode()){if(n.nodeValue.replace(/\s/g,'')!=='')ns.push(n);}if(!ns.length)return;var spans=[];for(var i=0;i<ns.length;i++){var txt=ns[i].nodeValue,frag=document.createDocumentFragment();for(var j=0;j<txt.length;j++){var s=document.createElement('span');s.textContent=txt[j];s.style.visibility='hidden';frag.appendChild(s);spans.push(s);}ns[i].parentNode.replaceChild(frag,ns[i]);}el.style.setProperty('visibility','visible','important');var pos=0,t=setInterval(function(){if(pos<spans.length){spans[pos].style.visibility='visible';pos++;}else{clearInterval(t);}},SPEED);}function init(){var els=document.querySelectorAll('.text-eyebrow');if(!els.length)return;var io=new IntersectionObserver(function(es){for(var i=0;i<es.length;i++){if(es[i].isIntersecting){typewrite(es[i].target);io.unobserve(es[i].target);}}},{threshold:0.3});for(var i=0;i<els.length;i++)io.observe(els[i]);}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();

/* ===================== loading_progress_v13-4.0.0.js ===================== */
(function(){var layer=document.querySelector('.page-loading-layer');if(!layer||getComputedStyle(layer).display==='none')return;var animDone=false;function startLenis(){if(window.lenis)window.lenis.start();}var lt=setInterval(function(){if(animDone){startLenis();clearInterval(lt);return;}var cs=getComputedStyle(layer);var r=layer.getBoundingClientRect();var show=cs.display!=='none'&&cs.visibility!=='hidden'&&parseFloat(cs.opacity)>0.05&&r.height>0&&r.bottom>0;if(window.lenis){show?window.lenis.stop():window.lenis.start();}if(!show){clearInterval(lt);}},100);var num=layer.querySelector('.loading_progress-number');var bar=layer.querySelector('.loading_progress-bar');if(!num||!bar)return;var dur=2000,start=performance.now(),loaded=false,loadedAt=0,CAP=2500,HARDMAX=5000;function setLoaded(){loaded=true;loadedAt=performance.now();}if(document.readyState==='complete'){setLoaded();}else{window.addEventListener('load',setLoaded);}function vidOk(){if(window.__heroVideoPlaying)return true;var v=document.querySelector('[data-video-url] video')||document.querySelector('video');if(!v)return true;if(!v.paused&&v.readyState>=2&&v.currentTime>0)return true;return loadedAt>0&&(performance.now()-loadedAt)>CAP;}function ease(t){return t<0.5?2*t*t:-1+(4-2*t)*t;}function finish(){layer.style.clipPath='inset(0 0 0% 0)';requestAnimationFrame(function(){requestAnimationFrame(function(){layer.style.transition='clip-path 0.8s cubic-bezier(0.76,0,0.24,1)';layer.style.clipPath='inset(0 0 100% 0)';setTimeout(function(){animDone=true;layer.style.display='none';startLenis();},850);});});}function tick(now){var el=now-start;var p=Math.min(el/dur,1);if(p<1){var pct=Math.floor(ease(p)*95);num.textContent=pct+'%';bar.style.width=pct+'%';requestAnimationFrame(tick);return;}if(el<HARDMAX&&(!loaded||!vidOk())){num.textContent='95%';bar.style.width='95%';requestAnimationFrame(tick);return;}num.textContent='100%';bar.style.width='100%';setTimeout(finish,300);}requestAnimationFrame(tick);})();

/* ===================== cases_swiper_dots_v13-1.0.0.js ===================== */
(function(){function init(){var sw=document.querySelector('.cases-swiper');if(!sw||!sw.swiper)return false;var s=sw.swiper;var loop=s.params.loop;var n=loop?s.slides.length-s.loopedSlides*2:s.slides.length;var cases=sw.closest('.cases-slider_component')||sw.closest('.cases_component')||sw.parentNode;if(!cases)return false;var pag=cases.querySelector('.pagination_component')||cases;var wrap=document.createElement('div');wrap.style.cssText='display:flex;gap:15px;align-items:flex-start;align-self:flex-start;margin-left:auto;';var ds=[];for(var i=0;i<n;i++){var d=document.createElement('div');d.style.cssText='width:10px;height:10px;border-radius:50%;background:#cccccc;flex-shrink:0;transition:background 0.3s ease;cursor:pointer;';(function(idx){d.addEventListener('click',function(){if(loop){s.slideToLoop(idx);}else{s.slideTo(idx);}});})(i);wrap.appendChild(d);ds.push(d);}pag.appendChild(wrap);function upd(){var idx=s.realIndex;var pv=Math.floor(parseFloat(s.params.slidesPerView)||1);var last=Math.min(idx+pv-1,n-1);ds.forEach(function(d,i){d.style.background=i<=last?'#f15a24':'#cccccc';});}upd();s.on('slideChange',upd);return true;}var t=setInterval(function(){if(init())clearInterval(t);},200);})();

/* ===================== herorevealmaskv2-2.0.0.js ===================== */
(function(){var DUR=800,STAGGER=130,EASE='cubic-bezier(0.16,1,0.3,1)';function reveal(el){var h=el.innerHTML;var p=h.split(/<br\s*\/?>/i);if(p.length<2){el.style.setProperty('visibility','visible','important');return;}var p1=p[0],p2=p.slice(1).join('');el.innerHTML='';function mk(html){var m=document.createElement('div');m.style.cssText='overflow:hidden;display:block;line-height:inherit';var i=document.createElement('div');i.style.cssText='transform:translateY(105%);display:block;line-height:inherit';i.innerHTML=html;m.appendChild(i);el.appendChild(m);return i;}var i1=mk(p1),i2=mk(p2);el.offsetHeight;el.style.setProperty('visibility','visible','important');requestAnimationFrame(function(){requestAnimationFrame(function(){i1.style.transition='transform '+DUR+'ms '+EASE;i1.style.transform='translateY(0)';setTimeout(function(){i2.style.transition='transform '+DUR+'ms '+EASE;i2.style.transform='translateY(0)';},STAGGER);});});}function init(){var e0=document.querySelector('.hero_title_0s'),e3=document.querySelector('.hero_title_3s');if(e0)e0.style.setProperty('visibility','hidden','important');if(e3)e3.style.setProperty('visibility','hidden','important');if(e0)setTimeout(function(){reveal(e0);},100);if(e3)setTimeout(function(){reveal(e3);},3000);}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();

/* ===================== uspslotv13-14.0.0.js ===================== */
(function(){var TR='transform 400ms cubic-bezier(0.4,0,0.2,1)';function setD(el,ch){var nc=el&&el.querySelector('.nc');if(!nc)return;while(nc.firstChild)nc.removeChild(nc.firstChild);var d=document.createElement('div');d.textContent=ch;nc.appendChild(d);}function wrap(el,ch){var t=el.textContent.trim();if(t.length<2)return;el.innerHTML='<span style="display:inline-block;vertical-align:top">'+t.slice(0,-1)+'</span><span class="nc" style="display:inline-block;overflow:hidden;vertical-align:top;height:1em;line-height:1"><span style="display:block">'+ch+'</span></span>';}function anim(el,fg,tg,dir){if(!el)return;var nc=el.querySelector('.nc');if(!nc)return;while(nc.firstChild)nc.removeChild(nc.firstChild);var fr=document.createElement('div'),to=document.createElement('div');fr.textContent=fg;to.textContent=tg;nc.appendChild(fr);nc.appendChild(to);if(dir>=0)to.style.transform='translateY(-200%)';fr.offsetHeight;fr.style.transition=to.style.transition=TR;if(dir<0){fr.style.transform=to.style.transform='translateY(-100%)';}else{fr.style.transform='translateY(100%)';to.style.transform='translateY(-100%)';}setTimeout(function(){fr.remove();to.style.transition='none';to.style.transform='';},420);}function init(){var sw=document.querySelector('.usp_component .swiper-container');if(!sw)return;var els=document.querySelectorAll('.usp_component .usp_number-big');var oa=[];for(var i=0;i<els.length;i++){var d=els[i].textContent.trim().slice(-1);oa.push(d);wrap(els[i],i>0?oa[i-1]:d);}var ti=setInterval(function(){if(sw.swiper){clearInterval(ti);var s=sw.swiper,at=null;s.on('slideChange',function(){if(at)clearTimeout(at);var pi=s.previousIndex,ai=s.activeIndex,dr=ai>pi?-1:1,fg=oa[pi],tg=oa[ai],a=s.slides[ai],ie=a&&a.querySelector('.usp_number-big');setD(ie,fg);at=setTimeout(function(){anim(ie,fg,tg,dr);},500);});}},100);}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();

/* ===================== servicetitleslideupv1-12.0.0.js ===================== */
(function(){var DUR='0.4s',EA='cubic-bezier(0.33,1,0.68,1)';function setup(t){if(!t||t._sl)return null;t._sl=true;var h=t.innerHTML;t.style.overflow='hidden';t.style.position='relative';t.style.display='block';var o=document.createElement('div');o.style.transform='translateY(0)';o.innerHTML=h;var c=document.createElement('div');c.style.cssText='position:absolute;top:0;left:0;width:100%;transform:translateY(105%)';c.innerHTML=h;t.innerHTML='';t.appendChild(o);t.appendChild(c);return{o:o,c:c,locked:false};}function init(){var hs=document.querySelectorAll('.service_header');var ps=[];for(var i=0;i<hs.length;i++){(function(h){var p=setup(h.querySelector('.service_title'));if(!p)return;ps.push(p);var tr='transform '+DUR+' '+EA;p.o.style.transition=tr;p.c.style.transition=tr;h.addEventListener('mouseenter',function(){if(p.locked||h.classList.contains('active'))return;p.o.style.transform='translateY(-105%)';p.c.style.transform='translateY(0)';});h.addEventListener('mouseleave',function(){if(p.locked)return;p.o.style.transform='translateY(0)';p.c.style.transform='translateY(105%)';});h.addEventListener('click',function(){if(p.locked){p.locked=false;p.o.style.transform='translateY(0)';p.c.style.transform='translateY(105%)';}else{p.locked=true;for(var j=0;j<ps.length;j++){if(ps[j]!==p){ps[j].locked=false;ps[j].o.style.transform='translateY(0)';ps[j].c.style.transform='translateY(105%)';}}}}); })(hs[i]);}};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();

/* ===================== uspactivev1-7.0.0.js ===================== */
(function(){var s=document.createElement('style');s.textContent='.usp_thumb .usp_number-small{transition:color 300ms ease}.usp_thumb:hover .usp_number-small{color:#fff!important}.usp_thumb.is-active .usp_number-small{color:#f15a24!important}';document.head.appendChild(s);function thumbOf(sl){if(!sl)return null;return sl.matches&&sl.matches('.usp_thumb')?sl:(sl.querySelector('.usp_thumb')||sl.closest('.usp_thumb'));}function apply(){var items=document.querySelectorAll('.usp_thumb');for(var i=0;i<items.length;i++)items[i].classList.remove('is-active');var a=document.querySelector('.gallery-thumbs .swiper-slide-thumb-active');var th=thumbOf(a);if(th)th.classList.add('is-active');}var n=0,t=setInterval(function(){var g=document.querySelector('.gallery-slider');if(g&&g.swiper){clearInterval(t);g.swiper.on('slideChange',function(){setTimeout(apply,60);});var gt=document.querySelector('.gallery-thumbs');if(gt&&gt.swiper)gt.swiper.on('slideChange',function(){setTimeout(apply,60);});setTimeout(apply,200);}else if(++n>100){clearInterval(t);}},100);})();

/* ===================== team_swiper_dots_v1-1.0.0.js ===================== */
(function(){function init(){var sw=document.querySelector('.team-swiper');if(!sw||!sw.swiper)return false;var s=sw.swiper;var loop=s.params.loop;var n=loop?s.slides.length-s.loopedSlides*2:s.slides.length;var pag=null,node=sw.parentNode;while(node&&node!==document.body){if(node.querySelector&&node.querySelector('.pagination_component')){pag=node.querySelector('.pagination_component');break;}node=node.parentNode;}if(!pag)pag=sw.parentNode;if(!pag)return false;var wrap=document.createElement('div');wrap.style.cssText='display:flex;gap:15px;align-items:flex-start;align-self:flex-start;margin-left:auto;';var ds=[];for(var i=0;i<n;i++){var d=document.createElement('div');d.style.cssText='width:10px;height:10px;border-radius:50%;background:#cccccc;flex-shrink:0;transition:background 0.3s ease;cursor:pointer;';(function(idx){d.addEventListener('click',function(){if(loop){s.slideToLoop(idx);}else{s.slideTo(idx);}});})(i);wrap.appendChild(d);ds.push(d);}pag.appendChild(wrap);function upd(){var idx=s.realIndex;var pv=Math.floor(parseFloat(s.params.slidesPerView)||1);var last=Math.min(idx+pv-1,n-1);ds.forEach(function(d,i){d.style.background=i<=last?'#f15a24':'#cccccc';});}upd();s.on('slideChange',upd);return true;}var t=setInterval(function(){if(init())clearInterval(t);},200);})();

/* ===================== cases_load_more_v2-1.0.0.js ===================== */
(function(){var MAX=4;var shown=MAX;var items=document.querySelectorAll('.cases_item');var btn=document.querySelector('#cases-load-more');if(!items.length||!btn)return;function update(animate){var newlyShown=[];items.forEach(function(item,i){if(i<shown){if(item.style.display==='none')newlyShown.push(item);item.style.display='';}else{item.style.display='none';}});if(animate&&newlyShown.length){newlyShown.forEach(function(item,idx){item.style.opacity='0';item.style.transform='translateY(2rem)';item.style.transition='none';requestAnimationFrame(function(){requestAnimationFrame(function(){item.style.transition='opacity 0.5s ease '+(idx*100)+'ms,transform 0.5s ease '+(idx*100)+'ms';item.style.opacity='1';item.style.transform='translateY(0)';});});});}btn.style.display=shown>=items.length?'none':'flex';}update(false);btn.addEventListener('click',function(){shown=Math.min(shown+MAX,items.length);update(true);});})();

/* ===================== form_validator_v10-1.0.0.js ===================== */
(function(){var s=document.createElement('style');s.textContent='.form-err{color:#f15a24;font-size:.9rem;font-weight:600;margin-top:-2rem;margin-bottom:1rem;display:none;width:fit-content}.form-err.show{display:block;margin-top:1rem;margin-bottom:0}.form_input.err{border-color:#f15a24!important;border-bottom-width:2px!important}#chk-e{margin-top:.5rem;margin-left:0}';document.head.appendChild(s);var form=document.getElementById('wf-form-Form');if(!form)return;var fields=[{id:'Name',rules:[{t:function(v){return v.trim().length>0},m:'Please enter your name.'},{t:function(v){return v.trim().length>=2},m:'Name must be at least 2 characters.'},{t:function(v){return v.trim().split(/\s+/).length>=2},m:'Please enter your first and last name.'}]},{id:'Email',rules:[{t:function(v){return v.trim().length>0},m:'Please enter your email address.'},{t:function(v){return/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)},m:'Please enter a valid email address.'}]},{id:'Message-3',rules:[{t:function(v){return v.trim().length>0},m:'Please enter your message.'},{t:function(v){return v.trim().length>=10},m:'Message is too short (min. 10 characters).'}]}];function addErr(id){var el=document.getElementById(id);if(!el)return;var e=document.createElement('div');e.className='form-err';e.id=id+'-e';el.parentNode.insertBefore(e,el.nextSibling);}fields.forEach(function(f){addErr(f.id);});var chk=document.getElementById('Checkbox');if(chk){var ce=document.createElement('div');ce.className='form-err';ce.id='chk-e';var cl=chk.closest('.w-checkbox')||chk.parentNode;cl.parentNode.insertBefore(ce,cl.nextSibling);}function vld(id){var f=fields.find(function(x){return x.id===id;});if(!f)return true;var el=document.getElementById(id),e=document.getElementById(id+'-e');if(!el||!e)return true;for(var i=0;i<f.rules.length;i++){if(!f.rules[i].t(el.value)){e.textContent=f.rules[i].m;e.classList.add('show');el.classList.add('err');return false;}}e.classList.remove('show');el.classList.remove('err');return true;}function vldChk(){if(!chk)return true;var e=document.getElementById('chk-e');if(!chk.checked){e.textContent='Please accept the terms and conditions.';e.classList.add('show');return false;}e.classList.remove('show');return true;}fields.forEach(function(f){var el=document.getElementById(f.id);if(!el)return;el.addEventListener('blur',function(){vld(f.id);});});if(chk)chk.addEventListener('change',vldChk);form.addEventListener('submit',function(e){var ok=true;fields.forEach(function(f){if(!vld(f.id))ok=false;});if(!vldChk())ok=false;if(!ok){e.preventDefault();e.stopPropagation();}},true);})();

/* ===================== form_submit_button_v1-1.0.0.js ===================== */
(function(){var real=document.getElementById('real-submit');if(!real)return;var form=real.closest('form');if(!form)return;var btn=form.querySelector('.button_primary');if(!btn)return;btn.addEventListener('click',function(e){e.preventDefault();real.click();});})();

